// Export utilities for LogicPy

export interface ExportOptions {
  filename?: string;
  includeComments?: boolean;
  includeTimestamp?: boolean;
}

// Download Python code as a .py file
export function downloadPythonFile(
  code: string, 
  options: ExportOptions = {}
): void {
  const {
    filename = 'logicpy_script.py',
    includeComments = true,
    includeTimestamp = true
  } = options;

  let content = '';

  // Add header comments
  if (includeComments) {
    content += '#!/usr/bin/env python3\n';
    content += '# -*- coding: utf-8 -*-\n';
    content += '\n';
    content += '# ============================================\n';
    content += '# Generated by LogicPy\n';
    content += '# The Logic-First Python Translator\n';
    content += '# ============================================\n';
    
    if (includeTimestamp) {
      content += `# Generated: ${new Date().toLocaleString()}\n`;
    }
    
    content += '\n';
  }

  // Add the actual code
  content += code;
  content += '\n';

  // Create and download the file
  const blob = new Blob([content], { type: 'text/x-python;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename.endsWith('.py') ? filename : `${filename}.py`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}

// Copy code to clipboard
export async function copyToClipboard(code: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(code);
    return true;
  } catch {
    return false;
  }
}

// Share code (using Web Share API if available)
export async function shareCode(code: string, title?: string): Promise<boolean> {
  if (!navigator.share) {
    return false;
  }

  try {
    await navigator.share({
      title: title || 'LogicPy Code',
      text: code
    });
    return true;
  } catch {
    return false;
  }
}

// Generate a shareable link (for future backend integration)
export function generateShareableLink(code: string): string {
  // For now, just encode in URL hash
  const encoded = btoa(encodeURIComponent(code));
  return `${window.location.origin}${window.location.pathname}#code=${encoded}`;
}

// Parse code from shareable link
export function parseCodeFromUrl(): string | null {
  const hash = window.location.hash;
  if (!hash.includes('code=')) {
    return null;
  }

  try {
    const encoded = hash.split('code=')[1];
    return decodeURIComponent(atob(encoded));
  } catch {
    return null;
  }
}

// Export as different formats
export function exportAsFormat(
  code: string, 
  format: 'py' | 'txt' | 'json',
  options: ExportOptions = {}
): void {
  let content = code;
  let mimeType = 'text/plain';
  let extension = format;

  switch (format) {
    case 'json':
      content = JSON.stringify({
        code,
        generatedAt: new Date().toISOString(),
        source: 'LogicPy'
      }, null, 2);
      mimeType = 'application/json';
      break;
    case 'py':
      mimeType = 'text/x-python';
      break;
    case 'txt':
    default:
      mimeType = 'text/plain';
      break;
  }

  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${options.filename || 'logicpy_code'}.${extension}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  URL.revokeObjectURL(url);
}
